#!/usr/bin/env bash
# Bash script to display DNS records: record type, IP, subdomains

print_rec () {
    local domain="$1"
    local subdomain="$2"

    local dig_output
    dig_output=$(dig +short "$subdomain.$domain")

    if [ -n "$dig_output" ]; then
        local record_type
        record_type=$(echo "$dig_output" | awk '{print $4}')

        local ip_address
        ip_address=$(echo "$dig_output" | awk '{print $1}')

        printf "The subdomain %s is a %s record and points to %s\n" "$subdomain" "$record_type" "$ip_address"
    else
        echo "No DNS record found for $subdomain.$domain"
    fi
}

domain="$1"

if [ -z "$2" ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
    for subdomain in "${subdomains[@]}"; do
        print_rec "$domain" "$subdomain"
    done
else
    print_rec "$domain" "$2"
fi
