#!/usr/bin/env bash

# This script displays information about subdomains of a given domain

# Function to display information for a specific subdomain
display_subdomain_info() {
	domain=$1
		subdomain=$2
		dig_output=$(dig $subdomain.$domain | awk '/ANSWER SECTION/{getline; print}')
		record_type=$(echo $dig_output | awk '{print $2}')
		destination=$(echo $dig_output | awk '{print $5}')
		echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Function to display information for default subdomains
display_default_subdomains_info() {
	domain=$1
		display_subdomain_info $domain "www"
		display_subdomain_info $domain "lb-01"
		display_subdomain_info $domain "web-01"
		display_subdomain_info $domain "web-02"
}

# Main function
main() {
	if [ $# -eq 1 ]; then
		display_default_subdomains_info $1
			elif [ $# -eq 2 ]; then
			display_subdomain_info $1 $2
	else
		echo "Usage: $0 domain [subdomain]"
			exit 1
			fi
}

# Execute main function with provided arguments
main "$@"

