#!/usr/bin/env bash
# uploads a file to a server

# Check if correct number of parameters is provided
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# Transfer the file to the server
scp -i "$ssh_key" -o StrictHostKeyChecking=no "$file_path" "$username@$server_ip":~/ 

# Check if file transfer was successful
if [ $? -eq 0 ]; then
    echo "File transfer successful."
else
    echo "Error: File transfer failed."
fi
