#!/usr/bin/env bash
# Installs nginx web server

if ! command -v nginx &>/dev/null; then
    apt-get update
    apt-get install -y nginx
fi

cat <<EOF > /etc/nginx/sites-available/redirect_me
server {
    listen 80;
    listen [::]:80;
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF

ln -sf /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

service nginx restart
