#!/usr/bin/env bash
# Installs nginx web server

if ! command -v nginx &>/dev/null; then
    apt-get update
    apt-get install -y nginx
fi

# Configure custom 404 page
cat <<EOF > /etc/nginx/sites-available/custom_404
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    error_page 404 /404.html;
    location = /404.html {
        root /usr/share/nginx/html;
        internal;
    }
}
EOF

# Create custom 404 page
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html >/dev/null

# Enable the new server block
ln -sf /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# Restart Nginx to apply the changes
service nginx restart
