#!/usr/bin/env bash

# Update package repositories and install Nginx
apt-get update
apt-get install -y nginx

# Modify Nginx configuration to listen on port 80
sed -i 's/80 default_server;/80;/g' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
service nginx restart

